spring.application.name=gastroflow
spring.datasource.url=jdbc:postgresql://localhost:5432/gastroflow
spring.datasource.username=postgres
spring.datasource.password=2662
spring.datasource.driver-class-name=org.postgresql.Driver
